// login constants
export const FB_LOGIN = 'FB_LOGIN';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const FB_LOGIN_FAIL = 'FB_LOGIN_FAIL';

export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL';

export const NORMAL_LOGIN = 'NORMAL_LOGIN';
export const NORMAL_LOGIN_SUCCESS = 'NORMAL_LOGIN_SUCCESS';
export const NORMAL_LOGIN_FAIL = 'NORMAL_LOGIN_FAIL';

// signup constants
export const FB_SIGNUP = 'FB_SIGNUP';
export const FB_SIGNUP_SUCCESS = 'FB_SIGNUP_SUCCESS';
export const FB_SIGNUP_FAIL = 'FB_SIGNUP_FAIL';

export const GOOGLE_SIGNUP = 'GOOGLE_SIGNUP';
export const GOOGLE_SIGNUP_SUCCESS = 'GOOGLE_SIGNUP_SUCCESS';
export const GOOGLE_SIGNUP_FAIL = 'GOOGLE_SIGNUP_FAIL';

export const NORMAL_SIGNUP = 'NORMAL_SIGNUP';
export const NORMAL_SIGNUP_SUCCESS = 'NORMAL_SIGNUP_SUCCESS';
export const NORMAL_SIGNUP_FAIL = 'NORMAL_SIGNUP_FAIL';